# Site content settings
title: Bashy Launchpage
logo_url: http://www.opensourcebash.org/img/sprites/logos-big.svg
claim: "Launchpage for OpenSource Projects"
description: > # this means to ignore newlines until "baseurl:"
  Gauge whether there is a bigger interest in your idea with this easy launch page, specifically designed for OpenSource Projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://launchpage.bashy.io" # the base hostname & protocol for your site
twitter_username: bashyHQ
github_username:  bashyHQ
facebook_page: ben
contact_email: " ben at create-build-execute dot com"

# theme and design settings

theme: babacao
hero_image: http://c1.staticflickr.com/5/4046/4333386510_89928d2553_b.jpg

sections:
  - features
  - stats
  - name: video_embed
    youtubeId: 8ItNE_DX6Cc
    pre: "## With Video Embeds"
    post: "**Markdown and custom content**"

# do you have another custom url the primary actions should go to? Put it here!
primary_action_target: "#signup"

# Build settings
markdown: kramdown


# plugins and stuff
gems:
  - jekyll-seo-tag
